using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RCapsSyncProcess.Migrations
{
    public partial class initLoad : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "iOP_Pipelines",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SapId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CountryName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Status = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ApprovalYear = table.Column<int>(type: "int", nullable: false),
                    ResponsibleCostCenter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FundCenter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WPA = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OperationType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegionDepartment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorDepartment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdbPublic = table.Column<double>(type: "float", nullable: true),
                    AdbPrivate = table.Column<double>(type: "float", nullable: true),
                    AdfLoan = table.Column<double>(type: "float", nullable: true),
                    AdfGrant = table.Column<double>(type: "float", nullable: true),
                    Mic = table.Column<double>(type: "float", nullable: true),
                    Tsf = table.Column<double>(type: "float", nullable: true),
                    AdfIncludingTsf = table.Column<double>(type: "float", nullable: true),
                    Ntf = table.Column<double>(type: "float", nullable: true),
                    CoFinancing = table.Column<double>(type: "float", nullable: true),
                    TrustFund = table.Column<double>(type: "float", nullable: true),
                    Total = table.Column<double>(type: "float", nullable: true),
                    FinancingSource = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedAfrica = table.Column<double>(type: "float", nullable: true),
                    LightUpAndPowerAfrica = table.Column<double>(type: "float", nullable: true),
                    IndustrializeAfrica = table.Column<double>(type: "float", nullable: true),
                    IntegrateAfrica = table.Column<double>(type: "float", nullable: true),
                    ImproveQualityOfLife = table.Column<double>(type: "float", nullable: true),
                    TotalHi = table.Column<double>(type: "float", nullable: true),
                    Confirm = table.Column<bool>(type: "bit", nullable: true),
                    FeedAfricaII = table.Column<double>(type: "float", nullable: true),
                    LightUpAndPowerAfricaII = table.Column<double>(type: "float", nullable: true),
                    IndustrializeAfricaII = table.Column<double>(type: "float", nullable: true),
                    IntegrateAfricaII = table.Column<double>(type: "float", nullable: true),
                    ImproveQualityOfLifeII = table.Column<double>(type: "float", nullable: true),
                    ReportDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ReportType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HighFivesImproveSector = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorAnalysis = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AfricanRegion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUa50_300M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CountryClassification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransitionVsNonTransitionStates = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeFactoAndNonDeFactoCountries = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InfrastructureVsSector = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Complex = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_iOP_Pipelines", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "LendingApprovals",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Country = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectTitle = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ResolutionNo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ApprovalDateYear = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Borrower = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorDept = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegionalDept = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorBoard = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FinancingSource_LEN = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Instrument = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Currency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ApprovedAmount_UAEquivalent = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SAPCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SAPNo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ApprovalMode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FinancingSource = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GroupKey1_SectorKey = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CountryClassification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransitionVsNonTransitionStates = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeFactoAndNonDeFactoCountries = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AfricanRegion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorAnalysis = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedAfrica = table.Column<double>(type: "float", nullable: true),
                    LightUpAndPowerAfrica = table.Column<double>(type: "float", nullable: true),
                    IndustrializeAfrica = table.Column<double>(type: "float", nullable: true),
                    IntegrateAfrica = table.Column<double>(type: "float", nullable: true),
                    ImproveQualityOfLife = table.Column<double>(type: "float", nullable: true),
                    TotalHI5 = table.Column<double>(type: "float", nullable: true),
                    Check = table.Column<bool>(type: "bit", nullable: true),
                    FinancingInstrument_USED = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FinancingInstrument = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Column2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InfrastructureVsSector = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InfrastructureVsSector_NOT_USED = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorDepartment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Complex = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OperationsKey = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OperationsType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumberOfProjects = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AmountInUAMillion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ApprovedAmount_USDEquivalent = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Selectivity_UA10M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Selectivity_UA20M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Selectivity_UA40M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Selectivity_UA50_300M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Column1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ApprovalMonthsAndYears = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Dec2015 = table.Column<double>(type: "float", nullable: true),
                    Dec2016 = table.Column<double>(type: "float", nullable: true),
                    Dec2017 = table.Column<double>(type: "float", nullable: true),
                    Dec2018 = table.Column<double>(type: "float", nullable: true),
                    Dec2019 = table.Column<double>(type: "float", nullable: true),
                    Dec2020 = table.Column<double>(type: "float", nullable: true),
                    Dec2021 = table.Column<double>(type: "float", nullable: true),
                    Dec2022 = table.Column<double>(type: "float", nullable: true),
                    Jun2023 = table.Column<double>(type: "float", nullable: true),
                    ImplementationStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImplementationStatus_ = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LendingApprovals", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "LendingPlan",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SapCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sector = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EsiaCategorization = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EsiaCategorizationDone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BoardDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ReadinessBpps = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Instrument = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Complex = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Country = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdbPublic = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdbPrivate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdfLoan = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdfGrant = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdfRo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tsf = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Adf = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ntf = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalProjectedApprovalUa = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FinancingSource = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Region = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorDepartment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalProjectedApprovalUsd = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalProjectedApprovalUaM = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalProjectedApprovalUsd2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedAfricaPtly = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LightUpAndPowerAfricaPtly = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IndustrializeAfricaPtly = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IntegrateAfricaPtly = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImproveQualityOfLifePtly = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedAfrica = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LightUpAndPowerAfrica = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IndustrializeAfrica = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IntegrateAfrica = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImproveQualityOfLife = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hi5s = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChechHi5s = table.Column<bool>(type: "bit", nullable: true),
                    Operations = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CountryClassification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransitionVsNonTransitionStates = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AfricanRegion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeFactoAndNonDeFactoCountries = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FinancingInstrument = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorKey = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorFull = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorVsInfrastructure = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CspStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Period = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Type = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CountriesWithStrategyVacuum = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BoardQuarter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ReportDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ReportDateType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumberOfProjects = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EsiaCat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EsiaCatActual = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EsiaDisclosed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UaMillion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUa10M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUa20M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Instrument2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUa30M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUa40M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUa50To300M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DatePeriod = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TaskManager = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CheckingInPipeline = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsProjectBriefPreparedAndFiled = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsOfficialFinancingRequestReceived = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsTaskManagerAssigned = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEsOfficerAssigned = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TechnicalStudiesCompletedOrScheduled = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsBoardDateProposed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEsCategorizationPosted = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeliveryDateForPcn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Column1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectInitiationInSAP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectSchedulingInBPPS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ResourceAllocation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StudiesAndPreparatoryActivities = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectInitiationInSAP1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectSchedulingInBPPS2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ResourceAllocation2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StudiesAndPreparatoryActivities2 = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LendingPlan", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Portfolios",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SapCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LoanNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Country = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BorrowerCategory = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LongName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Division = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GroupKey1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GroupKey2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubSectorName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GroupKey3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubSubSectorName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CompanyCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LoanType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StatusOfProject = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ApprovalDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CommitmentDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PlannedFinalDisbursementDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EffectiveFirstDisbursement = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EntryIntoForce = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActualFirstDisbursement = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LatestDisbursement = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Currency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CapitalAppliedFor = table.Column<double>(type: "float", nullable: true),
                    ContractCapital = table.Column<double>(type: "float", nullable: true),
                    CapitalReduction = table.Column<double>(type: "float", nullable: true),
                    DisbursementObligation = table.Column<double>(type: "float", nullable: true),
                    ValueDatedCapital = table.Column<double>(type: "float", nullable: true),
                    NetLoan = table.Column<double>(type: "float", nullable: true),
                    DisbursementRatio = table.Column<double>(type: "float", nullable: true),
                    TotalCommitmentForTheLoan = table.Column<double>(type: "float", nullable: true),
                    TotalContractDisbursement = table.Column<double>(type: "float", nullable: true),
                    TotalUndisbursedContract = table.Column<double>(type: "float", nullable: true),
                    TskManagerName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OldLoanAgreementNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeOfSupervisionSummary = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SerialNoSupervisionSummary = table.Column<double>(type: "float", nullable: true),
                    ExecutingAgency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MainBorrower = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Guarantor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DateReceivedByBank = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditDueDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastSupervisionMission = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastSupervisionMissionEndDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CurrentExpectedCompletionDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumberOfContracts = table.Column<double>(type: "float", nullable: true),
                    NumberOfAmendments = table.Column<double>(type: "float", nullable: true),
                    PlannedProjectCompletionDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectCost = table.Column<double>(type: "float", nullable: true),
                    ProjectCurrency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PurposeOfLoan = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UserStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADFFundNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    INT4 = table.Column<double>(type: "float", nullable: true),
                    RegionalDepartment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Region = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Status = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LoansExchangeRateDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MissionComplex = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorDepartment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BasicDatesDuration = table.Column<double>(type: "float", nullable: true),
                    InternalUoM = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Window = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AmountForWindow = table.Column<double>(type: "float", nullable: true),
                    CompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DelayNoSPVS = table.Column<double>(type: "float", nullable: true),
                    DelaySignMonth = table.Column<double>(type: "float", nullable: true),
                    DelayEffMonth = table.Column<double>(type: "float", nullable: true),
                    DelayDisbMonth = table.Column<double>(type: "float", nullable: true),
                    DelayClosMonth = table.Column<double>(type: "float", nullable: true),
                    ImplementationProgress = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DevelopmentObjectives = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PFIStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectAgeInYears = table.Column<double>(type: "float", nullable: true),
                    Description4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OriginalClosingDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumberOfExtensions = table.Column<double>(type: "float", nullable: true),
                    DurationExtensionFinalDisbursementDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CountryInvolved = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BusinessPartnerForBO = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BOText = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BusinessPartnerForGU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GUTex = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    YearTrend = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeOfProjectCalendarYear = table.Column<double>(type: "float", nullable: true),
                    StatusProject = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumberOfProject = table.Column<double>(type: "float", nullable: true),
                    FinancingInstrument = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeOfOperations = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeSpectrum = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RefineCountry = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Country2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SNDR = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SectorUsed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConfirmedAge = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DaysBetweenApprovalAndCompletion = table.Column<double>(type: "float", nullable: true),
                    AverageApprovalCompletionDurations = table.Column<double>(type: "float", nullable: true),
                    DaysBetweenApprovalAndEffectiveness = table.Column<double>(type: "float", nullable: true),
                    AverageApprovalEffectivenessDurations = table.Column<double>(type: "float", nullable: true),
                    AbsoluteAgeRange = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Disbursement_Ratio = table.Column<double>(type: "float", nullable: true),
                    AmountInUAMillion = table.Column<double>(type: "float", nullable: true),
                    AmountInUSDMillion = table.Column<double>(type: "float", nullable: true),
                    AmountDisbursedInUAMillion = table.Column<double>(type: "float", nullable: true),
                    DisbursedBalanceInUAMillion = table.Column<double>(type: "float", nullable: true),
                    FinancialWindow = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Years = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OperationsType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AfricanRegion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TransitionVsNonTransitionalStates = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DeFactoAndNonDeFactoCountries = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Complex = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DisbursementRatioSpectrum = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DisbursementRatioSpectrumFourRange = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUA10M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUA20M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUA30M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUA40M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelectivityUA50To300M = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MTRCondition = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalContractProcAmount = table.Column<double>(type: "float", nullable: true),
                    TotalAlert = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TypeAlert = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ExplanationFirstIndicator = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RefinedTypeAlert = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ReasonsForDelay = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Recommendations = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    KeyDelayIndicators = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    KeyRecommendedActions = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StatusOfProjectImplementationForAgedProjects = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhaseOfImplementation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ExpectedCompletionDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PCRDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PCRDueDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PCRTimeliness = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FirstIPR2023 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SecondIPR2023 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FirstIPR2022 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SecondIPR2022 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IPFStatus2023 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeData10Years = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentCategory = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentCategory2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentCategoryType = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Portfolios", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserFiles",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FileName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AddedDate = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserFiles", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "iOP_Pipelines");

            migrationBuilder.DropTable(
                name: "LendingApprovals");

            migrationBuilder.DropTable(
                name: "LendingPlan");

            migrationBuilder.DropTable(
                name: "Portfolios");

            migrationBuilder.DropTable(
                name: "UserFiles");
        }
    }
}
