// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCapsSyncProcess.DataContext;

#nullable disable

namespace RCapsSyncProcess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231226071649_initLoad")]
    partial class initLoad
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RCapsSyncProcess.Models.IOP_Pipeline", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AdbPrivate")
                        .HasColumnType("float");

                    b.Property<double?>("AdbPublic")
                        .HasColumnType("float");

                    b.Property<double?>("AdfGrant")
                        .HasColumnType("float");

                    b.Property<double?>("AdfIncludingTsf")
                        .HasColumnType("float");

                    b.Property<double?>("AdfLoan")
                        .HasColumnType("float");

                    b.Property<string>("AfricanRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApprovalYear")
                        .HasColumnType("int");

                    b.Property<double?>("CoFinancing")
                        .HasColumnType("float");

                    b.Property<string>("Complex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Confirm")
                        .HasColumnType("bit");

                    b.Property<string>("CountryClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeFactoAndNonDeFactoCountries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FeedAfrica")
                        .HasColumnType("float");

                    b.Property<double?>("FeedAfricaII")
                        .HasColumnType("float");

                    b.Property<string>("FinancingSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighFivesImproveSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ImproveQualityOfLife")
                        .HasColumnType("float");

                    b.Property<double?>("ImproveQualityOfLifeII")
                        .HasColumnType("float");

                    b.Property<double?>("IndustrializeAfrica")
                        .HasColumnType("float");

                    b.Property<double?>("IndustrializeAfricaII")
                        .HasColumnType("float");

                    b.Property<string>("InfrastructureVsSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("IntegrateAfrica")
                        .HasColumnType("float");

                    b.Property<double?>("IntegrateAfricaII")
                        .HasColumnType("float");

                    b.Property<double?>("LightUpAndPowerAfrica")
                        .HasColumnType("float");

                    b.Property<double?>("LightUpAndPowerAfricaII")
                        .HasColumnType("float");

                    b.Property<double?>("Mic")
                        .HasColumnType("float");

                    b.Property<double?>("Ntf")
                        .HasColumnType("float");

                    b.Property<string>("OperationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleCostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUa50_300M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("TotalHi")
                        .HasColumnType("float");

                    b.Property<string>("TransitionVsNonTransitionStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TrustFund")
                        .HasColumnType("float");

                    b.Property<double?>("Tsf")
                        .HasColumnType("float");

                    b.Property<string>("WPA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("iOP_Pipelines");
                });

            modelBuilder.Entity("RCapsSyncProcess.Models.LendingApprovals", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfricanRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountInUAMillion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalDateYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalMonthsAndYears")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ApprovedAmount_UAEquivalent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedAmount_USDEquivalent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Borrower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Check")
                        .HasColumnType("bit");

                    b.Property<string>("Column1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeFactoAndNonDeFactoCountries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Dec2015")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2016")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2017")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2018")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2019")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2020")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2021")
                        .HasColumnType("float");

                    b.Property<double?>("Dec2022")
                        .HasColumnType("float");

                    b.Property<string>("DocumentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FeedAfrica")
                        .HasColumnType("float");

                    b.Property<string>("FinancingInstrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancingInstrument_USED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancingSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancingSource_LEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKey1_SectorKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationStatus_")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ImproveQualityOfLife")
                        .HasColumnType("float");

                    b.Property<double?>("IndustrializeAfrica")
                        .HasColumnType("float");

                    b.Property<string>("InfrastructureVsSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfrastructureVsSector_NOT_USED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("IntegrateAfrica")
                        .HasColumnType("float");

                    b.Property<double?>("Jun2023")
                        .HasColumnType("float");

                    b.Property<double?>("LightUpAndPowerAfrica")
                        .HasColumnType("float");

                    b.Property<string>("NumberOfProjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationsKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationsType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionalDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selectivity_UA10M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selectivity_UA20M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selectivity_UA40M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selectivity_UA50_300M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalHI5")
                        .HasColumnType("float");

                    b.Property<string>("TransitionVsNonTransitionStates")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LendingApprovals");
                });

            modelBuilder.Entity("RCapsSyncProcess.Models.LendingPlan", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdbPrivate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdbPublic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdfGrant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdfLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdfRo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfricanRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardQuarter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChechHi5s")
                        .HasColumnType("bit");

                    b.Property<string>("CheckingInPipeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountriesWithStrategyVacuum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CspStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeFactoAndNonDeFactoCountries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryDateForPcn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsiaCat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsiaCatActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsiaCategorization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsiaCategorizationDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsiaDisclosed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedAfrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedAfricaPtly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancingInstrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancingSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hi5s")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImproveQualityOfLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImproveQualityOfLifePtly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustrializeAfrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustrializeAfricaPtly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrateAfrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrateAfricaPtly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsBoardDateProposed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEsCategorizationPosted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEsOfficerAssigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOfficialFinancingRequestReceived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProjectBriefPreparedAndFiled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsTaskManagerAssigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LightUpAndPowerAfrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LightUpAndPowerAfricaPtly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ntf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfProjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectInitiationInSAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectInitiationInSAP1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectSchedulingInBPPS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectSchedulingInBPPS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadinessBpps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportDateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceAllocation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorVsInfrastructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUa10M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUa20M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUa30M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUa40M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUa50To300M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudiesAndPreparatoryActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudiesAndPreparatoryActivities2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalStudiesCompletedOrScheduled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalProjectedApprovalUa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalProjectedApprovalUaM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalProjectedApprovalUsd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalProjectedApprovalUsd2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransitionVsNonTransitionStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tsf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UaMillion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LendingPlan");
                });

            modelBuilder.Entity("RCapsSyncProcess.Models.Portfolio", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADFFundNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbsoluteAgeRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualFirstDisbursement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfricanRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeData10Years")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AgeOfProjectCalendarYear")
                        .HasColumnType("float");

                    b.Property<string>("AgeSpectrum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AmountDisbursedInUAMillion")
                        .HasColumnType("float");

                    b.Property<double?>("AmountForWindow")
                        .HasColumnType("float");

                    b.Property<double?>("AmountInUAMillion")
                        .HasColumnType("float");

                    b.Property<double?>("AmountInUSDMillion")
                        .HasColumnType("float");

                    b.Property<string>("ApprovalDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditDueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AverageApprovalCompletionDurations")
                        .HasColumnType("float");

                    b.Property<double?>("AverageApprovalEffectivenessDurations")
                        .HasColumnType("float");

                    b.Property<string>("BOText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BasicDatesDuration")
                        .HasColumnType("float");

                    b.Property<string>("BorrowerCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPartnerForBO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPartnerForGU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CapitalAppliedFor")
                        .HasColumnType("float");

                    b.Property<double?>("CapitalReduction")
                        .HasColumnType("float");

                    b.Property<string>("CommitmentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmedAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ContractCapital")
                        .HasColumnType("float");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryInvolved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentExpectedCompletionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateReceivedByBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DaysBetweenApprovalAndCompletion")
                        .HasColumnType("float");

                    b.Property<double?>("DaysBetweenApprovalAndEffectiveness")
                        .HasColumnType("float");

                    b.Property<string>("DeFactoAndNonDeFactoCountries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DelayClosMonth")
                        .HasColumnType("float");

                    b.Property<double?>("DelayDisbMonth")
                        .HasColumnType("float");

                    b.Property<double?>("DelayEffMonth")
                        .HasColumnType("float");

                    b.Property<double?>("DelayNoSPVS")
                        .HasColumnType("float");

                    b.Property<double?>("DelaySignMonth")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentObjectives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DisbursedBalanceInUAMillion")
                        .HasColumnType("float");

                    b.Property<double?>("DisbursementObligation")
                        .HasColumnType("float");

                    b.Property<double?>("DisbursementRatio")
                        .HasColumnType("float");

                    b.Property<string>("DisbursementRatioSpectrum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisbursementRatioSpectrumFourRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Disbursement_Ratio")
                        .HasColumnType("float");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationExtensionFinalDisbursementDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectiveFirstDisbursement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryIntoForce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentCategory2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentCategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedCompletionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplanationFirstIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialWindow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancingInstrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstIPR2022")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstIPR2023")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUTex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKey1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKey2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKey3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guarantor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("INT4")
                        .HasColumnType("float");

                    b.Property<string>("IPFStatus2023")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalUoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyDelayIndicators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyRecommendedActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSupervisionMission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSupervisionMissionEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestDisbursement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoansExchangeRateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MTRCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainBorrower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionComplex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NetLoan")
                        .HasColumnType("float");

                    b.Property<double?>("NumberOfAmendments")
                        .HasColumnType("float");

                    b.Property<double?>("NumberOfContracts")
                        .HasColumnType("float");

                    b.Property<double?>("NumberOfExtensions")
                        .HasColumnType("float");

                    b.Property<double?>("NumberOfProject")
                        .HasColumnType("float");

                    b.Property<string>("OldLoanAgreementNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationsType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalClosingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCRDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCRDueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCRTimeliness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFIStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhaseOfImplementation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannedFinalDisbursementDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannedProjectCompletionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProjectAgeInYears")
                        .HasColumnType("float");

                    b.Property<double?>("ProjectCost")
                        .HasColumnType("float");

                    b.Property<string>("ProjectCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOfLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonsForDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefineCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefinedTypeAlert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionalDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNDR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondIPR2022")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondIPR2023")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUA10M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUA20M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUA30M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUA40M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectivityUA50To300M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SerialNoSupervisionSummary")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfProjectImplementationForAgedProjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSubSectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAlert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalCommitmentForTheLoan")
                        .HasColumnType("float");

                    b.Property<double?>("TotalContractDisbursement")
                        .HasColumnType("float");

                    b.Property<double?>("TotalContractProcAmount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalUndisbursedContract")
                        .HasColumnType("float");

                    b.Property<string>("TransitionVsNonTransitionalStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TskManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAlert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfOperations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfSupervisionSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ValueDatedCapital")
                        .HasColumnType("float");

                    b.Property<string>("Window")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearTrend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Years")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("RCapsSyncProcess.Models.UserFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
